### PR TITLE
Fixes: TypeError: node.serializeToString is not a function

### PR DESCRIPTION
**Pull request by johanneswuerbach**
The following code `return new XmlDom.XMLSerializer().serializeToString(doc.documentElement);` broke in 0.1.20 (worked in 0.1.19).

```
TypeError: node.serializeToString is not a function
```

This fixes the error introduced here https://github.com/jindw/xmldom/commit/447e45eaf1c8caa8217bb069948d0fa5504b1c50

Fixes https://github.com/jindw/xmldom/issues/146

### CODE REVIEW

**Comment by jindw** [comment]
thanks！
